# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6016e6c8f5bfbc4a2a27f458a857d4b8f8d955bc8c4423b886ec638311e6fd6c77f16e91bb7c3ddd5dc71054aad24d894541c1c06fcbee17f85760b7b3de65c1

test:
  secret_key_base: 34e67b60b29561641d43be6ffde20a79f15561c2c270dc5c9b4047b473cffbef5c754861fda60744ed1baacf9182c22f4dc58f84442c147742af44691137bc91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
